### ISSUE TITLE
Can the collector "find" specify -nouser and -nogroup, which are options of the find command?

### ISSUE THREAD

**Issue by mnrkbys** [tclahr/uac#300]
The `-nouser` and `-nogroup` options can easily find files with unknown UID or GID.

**Comment by tclahr** [comment]
According to my tests, only ESXi and a few Linux such as OpenWRT do not support `-nouser` and `-nogroup`. I was even able to add those 2 options to `find_pl` tool.

I think the best option would be making 2 new options available for the artifacts (`no_user` and `no_group`), such as:

`no_user`: a boolean (true or false) property that would add `-nouser` parameter to `find` when `true`.
`no_group`: a boolean (true or false) property that would add `-nogroup` parameter to `find` when `true`.

Examples: 

```yaml
version: 1.0
output_directory: /live_response/system
artifacts:
  -
    description: List all files that do not have a valid owner (i.e., their UID does not match any existing user on the system).
    supported_os: [all]
    collector: find
    path: /
    no_user: true
    output_file: no_user_files.txt
```

```yaml
version: 1.0
output_directory: /live_response/system
artifacts:
  -
    description: List all files that do not have a valid group (i.e., their group ID does not match any existing group on the system).
    supported_os: [all]
    collector: find
    path: /
    no_group: true
    output_file: no_group_files.txt
```

What are you thoughts?
