### ISSUE TITLE
max_file_size is ignored/useless if file_type is not specified to f

### ISSUE THREAD

**Issue by william-billaud** [tclahr/uac#338]
If file type is not specified, directory will also be collected (as it will be returned by find command and then expended).
As max_file_size is only applied to the find command and not when directory content is expended for collection, in most artefact this value is useless, as even file exceding size will be collected.

For example the following artifact : https://github.com/tclahr/uac/blob/main/artifacts/files/logs/var_log.yaml will collect a lastlog file of multiple Go but the following won't.

```yaml
version: 3.0
artifacts:
  -
    description: Collect /var/log logs.
    supported_os: [aix, esxi, freebsd, linux, netbsd, netscaler, openbsd, solaris]
    collector: file
    path: /var/log
    file_type: [f]
    max_file_size: 1073741824 # 1GB
  -
    description: Collect /private/var/log logs.
    supported_os: [macos]
    collector: file
    path: /private/var/log
    file_type: [f]
    max_file_size: 1073741824 # 1GB
```

I'm not sure if this is the intended comportment. If not I see two ways of fixing it
* Adding file type to all artifacts
* Set default values of file_type to f.
